"""Export the computational cells of notebook 08 to a tmux-friendly runner.

The notebook remains the readable specification. This exporter selects the
non-plotting cells and injects command-line overrides before the experiment
signature is computed.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "notebooks" / "08_similarity_reflection_threshold.ipynb"
TARGET = ROOT / "run_similarity_threshold.py"


HEADER = r'''#!/usr/bin/env python
"""Run the notebook-08 similarity-threshold experiment without Jupyter.

This file is generated by scripts/export_notebook08_runner.py. Regenerate it
after changing the computational cells in notebook 08.
"""

from __future__ import annotations

import argparse
import multiprocessing
import os


def parse_args():
    parser = argparse.ArgumentParser(
        description="Single-memory reflection experiment across similarity levels."
    )
    parser.add_argument("--models", help="Comma-separated model keys; defaults to notebook config.")
    parser.add_argument("--datasets", help="Comma-separated dataset names; defaults to notebook config.")
    parser.add_argument("--gpu", default=os.environ.get("RMCQ_NOTEBOOK_GPU", "3"))
    parser.add_argument("--validation-cap", type=int, help="Maximum validation items per dataset.")
    parser.add_argument("--batch-size", type=int, help="Generation checkpoint batch size.")
    parser.add_argument("--bootstrap-curve", type=int, help="Bootstrap replicates for effect curves.")
    parser.add_argument("--bootstrap-policy", type=int, help="Bootstrap replicates for held-out policies.")
    parser.add_argument("--output-root", help="Alternative directory for versioned experiment outputs.")
    parser.add_argument("--fresh", action="store_true", help="Ignore generation caches and overwrite this run.")
    return parser.parse_args()


def display(value):
    """Plain-text replacement for IPython display in tmux logs."""
    if hasattr(value, "to_string"):
        print(value.to_string(index=False), flush=True)
    else:
        print(value, flush=True)
'''


MAIN_PREFIX = r'''
ARGS = parse_args()
os.environ["RMCQ_NOTEBOOK_GPU"] = str(ARGS.gpu)
os.environ.setdefault("MPLBACKEND", "Agg")
'''


OVERRIDES = r'''
# ---------------------------------------------------------------------------
# Command-line overrides. They run before EXPERIMENT_ID is computed, so every
# materially different configuration receives a different output directory.
# ---------------------------------------------------------------------------
if ARGS.models:
    STUDENT_MODELS = [x.strip() for x in ARGS.models.split(",") if x.strip()]
if ARGS.datasets:
    DATASETS = [x.strip() for x in ARGS.datasets.split(",") if x.strip()]
if ARGS.validation_cap is not None:
    N_VALIDATION_PER_DATASET = ARGS.validation_cap
if ARGS.batch_size is not None:
    GENERATION_BATCH_SIZE = ARGS.batch_size
if ARGS.bootstrap_curve is not None:
    N_BOOTSTRAP_CURVE = ARGS.bootstrap_curve
if ARGS.bootstrap_policy is not None:
    N_BOOTSTRAP_POLICY = ARGS.bootstrap_policy
if ARGS.output_root:
    RESULTS_ROOT = Path(ARGS.output_root).expanduser().resolve()
RESUME = not ARGS.fresh

print("CLI models:", STUDENT_MODELS, flush=True)
print("CLI datasets:", DATASETS, flush=True)
print("CLI GPU:", ARGS.gpu, "resume:", RESUME, flush=True)
'''


FOOTER = r'''
print("\nExperiment completed successfully.", flush=True)
print("Experiment directory:", OUT_DIR, flush=True)
print("Open notebooks/08_similarity_reflection_threshold_plots.ipynb to inspect the results.", flush=True)
'''


GUARD = r'''
if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()
'''


def source(cell: dict) -> str:
    value = cell.get("source", "")
    return "".join(value) if isinstance(value, list) else value


notebook = json.loads(NOTEBOOK.read_text(encoding="utf-8"))

# Computational pipeline only. Cells 16+ contain plotting and notebook-only
# presentation. The override is inserted after configuration cell 2 and before
# prompt/signature cell 4.
selected = [1, 2, 4, 6, 8, 10, 11, 13, 14]
body_sections = [MAIN_PREFIX]
for index in selected:
    if index == 4:
        body_sections.append(OVERRIDES)
    body_sections.append(f"\n\n# %% [notebook cell {index}]\n" + source(notebook["cells"][index]).rstrip())
body_sections.append(FOOTER)

body = "\n".join(body_sections).strip()
indented_body = "\n".join(("    " + line) if line else "" for line in body.splitlines())
sections = [HEADER.rstrip(), "\n\ndef main():\n" + indented_body, "\n\n" + GUARD.strip()]

TARGET.write_text("\n".join(sections).rstrip() + "\n", encoding="utf-8")
print(f"exported {TARGET}")
